language: java
before_install:
  - export SORCER_HOME=`pwd`
  - export RIO_HOME=$SORCER_HOME/target/rio
  - echo "SORCER_HOME is $SORCER_HOME"
  - echo "RIO_HOME is $RIO_HOME"
install: mvn -P disttest install
script:
  - bin/sorcer-boot -Psorcer
  - mvn test -Prun-its
  - kill `jps|grep Sorcer|cut -d' ' -f1`
  - cd distribution/target/sorcer-*/sorcer-*/
  - export SORCER_HOME=`pwd`
  - unset RIO_HOME
  - export -n RIO_HOME
  - cd -
  - bin/test-examples.sh
after_script:
  - kill `jps|grep Sorcer|cut -d' ' -f1`
jdk:
  - oraclejdk7
# whitelist
branches:
  only:
    - v1.0-M4

notifications:
  email:
    - sorcer-devel@lists.sourceforge.net
